name: jaguar_session_mongo
description: MongoDb based session manager for Jaguar.dart. Stores session data in a MongoDb collection.
version: 2.1.1
homepage: https://github.com/Jaguar-dart/session
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  mongo_dart: ^0.3.2
  jaguar: ^2.1.20
  jaguar_serializer: ^2.1.8
  crypto: ^2.0.2
  jaguar_data_store: ^2.1.1
  jaguar_mongo_data_store: ^2.1.1

dev_dependencies:
  test: ^1.2.0
  jaguar_auth: ^2.1.1
  auth_header: ^0.0.2
  jaguar_reflect: ^2.1.1
  jaguar_mongo: ^2.1.1
  jaguar_example_session_models:
    path: ../example_models
