name: jaguar_session_mongo
description: MongoDb based session manager for Jaguar.dart. Stores session data in a MongoDb collection.
version: 1.3.1
homepage: https://github.com/Jaguar-dart/jaguar_session_mongo
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  mongo_dart: ^0.3.0
  jaguar: ^1.3.4
  jaguar_mongo: ^1.3.1
  jaguar_data_store: ^0.5.2
  jaguar_mongo_data_store: ^1.3.2
  jaguar_serializer: ^0.5.1
  crypto: ^2.0.2

dev_dependencies:
  test: ^0.12.0
  jaguar_auth: ^1.3.2
  auth_header: ^0.0.2
  jaguar_reflect: ^1.3.1
