name: jaguar_example_session_models
description: Models for examples demonstrating sessions and authentication using Jaguar.
version: 2.1.5
homepage: https://github.com/Jaguar-dart/session
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  jaguar_serializer: ^2.1.8
  jaguar: ^2.1.24
  jaguar_auth: ^2.1.1
  jaguar_common: ^2.1.1

dev_dependencies:
  test: ^1.2.0
  build_runner: ^0.9.0
  jaguar_serializer_cli: ^2.1.24
