name: jaguar_session_jwt
description: JWT session managers for Jaguar
version: 1.3.2
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_session_jwt

documentation:

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  auth_header: ^0.0.2
  jaguar: ^1.3.4
  jaguar_jwt: ^1.1.5

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  jaguar_client: ^0.2.0
  jaguar_serializer: ^0.5.0
  jaguar_json: ^1.3.1
  http: ^0.11.3
  jaguar_auth: ^1.3.2
  jaguar_common: ^0.2.1
  jaguar_reflect: ^1.3.2
