name: jaguar_session_jwt
description: JWT session managers for Jaguar
version: 2.1.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_session_jwt

documentation:

environment:
  sdk: ">=2.0.0-dev.60.0 <3.0.0"

dependencies:
  auth_header: ^0.0.2
  jaguar: ^2.1.18
  jaguar_jwt: ^1.1.5

dev_dependencies:
  test: ^1.2.0
  # jaguar_client: ^0.2.0
  jaguar_serializer: ^2.1.8
  # jaguar_json: ^1.3.1
  http: ^0.11.3
  jaguar_auth: ^2.1.1
  jaguar_common: ^0.2.1
  jaguar_reflect: ^2.1.1
