# This file allows you to configure the Dart analyzer.
#
# The commented part below is just for inspiration. Read the guide here:
#   https://www.dartlang.org/guides/language/analysis-options

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # see catalog here: http://dart-lang.github.io/linter/lints/
    - always_put_control_body_on_new_line
    - camel_case_types
    # - omit_local_variable_types
    - prefer_single_quotes
    - public_member_api_docs
    - sort_constructors_first
    - type_annotate_public_apis
